executor: CeleryExecutor
airflow:
  image:
    repository: apache/airflow
  config:
    AIRFLOW__CORE__FERNET_KEY: 'qNsbDaiqY1ECxKYXGiTIJhIkUv7lR7yTN-wNtMZDY_0='
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__WEB_SERVER_HOST: '0.0.0.0'
  dags:
    path: /opt/airflow/dags
  logs:
    path: /opt/airflow/logs
postgresql:
  enabled: true
redis:
  enabled: true
webserver:
  service:
    type: LoadBalancer

