executor: CeleryExecutor
airflow:
  image:
    repository: apache/airflow
  config:
    AIRFLOW__CORE__FERNET_KEY: 'qNsbDaiqY1ECxKYXGiTIJhIkUv7lR7yTN-wNtMZDY_0='
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  dags:
    path: /opt/airflow/dags
  logs:
    path: /opt/airflow/logs
postgresql:
  enabled: true  # Disable built-in PostgreSQL
# externalDatabase:
#   type: postgres
#   host: postgres.default.svc.cluster.local
#   port: 5432
#   database: airflow
#   user: airflow
#   password: airflow
redis:
  enabled: true  # Disable built-in Redis
# externalRedis:
#   host: redis.default.svc.cluster.local
#   port: 6379
webserver:
  service:
    type: LoadBalancer
  #port: 8080

