apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-shared-pv
spec:
  capacity:
    storage: 10Gi  # Adjust to your required storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/disks/airflow-shared  # Specify a valid local path in your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - <node-name>  # The node where the volume should be available
